doctrine:
    dbal:
        default_connection: common
        connections:
            common:
                url: '%env(resolve:DATABASE_URL)%'
                server_version: '8'
        types:
            uuid_type: App\Common\Infrastructure\Doctrine\Types\UuidType
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: common
        entity_managers:
            common:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                connection: common
                mappings:
                    Company_User:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Company/Domain/User'
                        prefix: 'App\Company\Domain\User'
                        alias: Company_User