framework:
    messenger:
        default_bus: command.bus

        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            query.bus: ~
            domain.event.bus: ~
            integration.event.bus: ~

        transports:
            sync: 'sync://'
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: 'doctrine://common?queue_name=failed'

        routing:
            App\Common\Domain\Bus\IntegrationEvent\IntegrationEvent: async