version: "3.1"
services:

  php:
    build: .docker/php
    container_name: symfony-ddd-php
    working_dir: /application
    volumes:
      - .:/application
      - ./.docker/php/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    ports:
      - "9000:9000"
    environment:
      - DATABASE_URL=${DATABASE_URL}

  nginx:
    image: nginx:alpine
    container_name: symfony-ddd-nginx
    working_dir: /application
    depends_on:
      - php
    volumes:
        - .:/application
        - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - .:/mysql/data
    ports:
      - "8282:80"
    
  mysql:
    image: mysql:8.0
    container_name: symfony-ddd-mysql
    working_dir: /mysql/data
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
